const asyncHandler = require("express-async-handler");
const AssessmentUpload = require("../models/webapp-models/assessmentuploadformModel");
const SatAssessment = require("../models/webapp-models/satAssessmentModel");
const Teacher = require("../models/webapp-models/teacherModel");
const AssessmentSubmission = require("../models/webapp-models/assessmentSubmissionModel");
const SatSubmission = require("../models/webapp-models/satSubmissionModel");
const SchoolAdmin = require("../models/webapp-models/schoolAdminModel");
const PDFDocument = require("pdfkit");

// Helper function to get school info based on user role
const getSchoolInfo = async (userId, userRole) => {
  if (userRole === "schoolAdmin") {
    const schoolAdmin = await SchoolAdmin.findById(userId).select("schoolName");
    return {
      schoolId: userId,
      schoolName: schoolAdmin?.schoolName || "School Admin"
    };
  } else if (userRole === "admin") {
    // Platform admin - need to specify which school to view
    // For now, we'll return first school or allow admin to view all
    const firstSchool = await SchoolAdmin.findOne().select("_id schoolName");
    if (firstSchool) {
      return {
        schoolId: firstSchool._id,
        schoolName: firstSchool.schoolName
      };
    }
    // If no schools exist, use admin's ID
    return {
      schoolId: userId,
      schoolName: "Platform Admin View"
    };
  }
  return null;
};

// @desc    Get all assessments generated by teachers in school
// @route   GET /api/school-admin/uploads
// @access  Private (School Admin or Platform Admin)
const getSchoolUploads = asyncHandler(async (req, res) => {
  try {
    const userId = req.user._id;
    const userRole = req.user.role;

    // ✅ Get school info based on user role
    const schoolInfo = await getSchoolInfo(userId, userRole);

    if (!schoolInfo) {
      return res.status(400).json({
        success: false,
        message: "Unable to determine school context"
      });
    }

    const { schoolId, schoolName } = schoolInfo;

    console.log("🔍 User:", userRole, "School:", schoolName, "ID:", schoolId);

    const {
      type = "all",
      teacherId,
      status,
      subject,
      gradeLevel,
      page = 1,
      limit = 20,
      sortBy = "createdAt",
      sortOrder = "desc"
    } = req.query;

    const skip = (parseInt(page) - 1) * parseInt(limit);
    const sort = {};
    sort[sortBy] = sortOrder === "asc" ? 1 : -1;

    // ✅ STEP 1: Find all teachers in this school
    const teacherFilter = { schoolId: schoolId };
    if (teacherId) {
      teacherFilter._id = teacherId;
    }

    const teachers = await Teacher.find(teacherFilter).select("_id name email");
    const teacherIds = teachers.map(teacher => teacher._id);

    console.log(`🔍 Found ${teacherIds.length} teachers in school`);

    if (teacherIds.length === 0) {
      return res.json({
        success: true,
        schoolName: schoolName,
        schoolId: schoolId,
        assessments: [],
        pagination: {
          total: 0,
          page: parseInt(page),
          limit: parseInt(limit),
          pages: 0
        },
        summary: {
          standard: 0,
          sat: 0,
          total: 0
        }
      });
    }

    // ✅ STEP 2: Build assessment query with teacher filter
    const baseQuery = {
      teacherId: { $in: teacherIds }
    };

    // Add additional filters
    if (status && status !== "all") {
      baseQuery.isApproved = status === "approved";
    }
    if (subject) baseQuery.subject = subject;
    if (gradeLevel) baseQuery.gradeLevel = gradeLevel;

    console.log("🔍 Assessment query:", JSON.stringify(baseQuery, null, 2));

    let standardAssessments = [];
    let satAssessments = [];
    let totalStandard = 0;
    let totalSat = 0;

    // Fetch standard assessments
    if (type === "all" || type === "standard") {
      const standardQuery = { ...baseQuery };

      [standardAssessments, totalStandard] = await Promise.all([
        AssessmentUpload.find(standardQuery)
          .populate({
            path: "teacherId",
            select: "name email"
          })
          .sort(sort)
          .skip(skip)
          .limit(type === "standard" ? parseInt(limit) : Math.floor(parseInt(limit) / 2))
          .lean(),
        AssessmentUpload.countDocuments(standardQuery)
      ]);

      console.log("📚 Standard Assessments Found:", standardAssessments.length);
    }

    // Fetch SAT assessments
    if (type === "all" || type === "sat") {
      const satQuery = { ...baseQuery };
      if (subject) satQuery.sectionType = subject;

      [satAssessments, totalSat] = await Promise.all([
        SatAssessment.find(satQuery)
          .populate({
            path: "teacherId",
            select: "name email"
          })
          .sort(sort)
          .skip(skip)
          .limit(type === "sat" ? parseInt(limit) : Math.floor(parseInt(limit) / 2))
          .lean(),
        SatAssessment.countDocuments(satQuery)
      ]);

      console.log("🎯 SAT Assessments Found:", satAssessments.length);
    }

    // Get submission counts
    const getSubmissionCounts = async (assessments, isSAT = false) => {
      const SubmissionModel = isSAT ? SatSubmission : AssessmentSubmission;

      return await Promise.all(
        assessments.map(async (assessment) => {
          const submissionCount = await SubmissionModel.countDocuments({
            assessmentId: assessment._id
          });
          return { ...assessment, submissionCount };
        })
      );
    };

    if (standardAssessments.length > 0) {
      standardAssessments = await getSubmissionCounts(standardAssessments, false);
    }

    if (satAssessments.length > 0) {
      satAssessments = await getSubmissionCounts(satAssessments, true);
    }

    // Create teacher map for quick lookup
    const teacherMap = {};
    teachers.forEach(teacher => {
      teacherMap[teacher._id.toString()] = {
        name: teacher.name,
        email: teacher.email
      };
    });

    // Format results
    const formatAssessments = (assessments, isSAT = false) => {
      return assessments.map(assessment => {
        const teacherInfo = teacherMap[assessment.teacherId?.toString()] ||
          assessment.teacherId ||
          { name: "Unknown", email: "No Email" };

        return {
          _id: assessment._id,
          type: isSAT ? "sat" : "standard",
          name: isSAT ? assessment.satTitle : assessment.assessmentName,
          title: isSAT ? assessment.satTitle : assessment.assessmentName,
          subject: isSAT ? assessment.sectionType : assessment.subject,
          gradeLevel: assessment.gradeLevel || "N/A",
          difficulty: assessment.difficulty,
          teacherName: teacherInfo.name || "Unknown",
          teacherEmail: teacherInfo.email || "No Email",
          teacherId: assessment.teacherId?._id || assessment.teacherId,
          isApproved: assessment.isApproved,
          status: assessment.status || "draft",
          createdAt: assessment.createdAt,
          questions: assessment.questions?.length || 0,
          submissionCount: assessment.submissionCount || 0,
          fileType: assessment.fileType || "pdf",
          timeLimit: assessment.timeLimit,
          tags: assessment.tags || [],
          schoolId: assessment.schoolId
        };
      });
    };

    let allAssessments = [];
    if (type === "all") {
      allAssessments = [...formatAssessments(standardAssessments, false),
      ...formatAssessments(satAssessments, true)];
      allAssessments.sort((a, b) => sortOrder === "asc"
        ? new Date(a.createdAt) - new Date(b.createdAt)
        : new Date(b.createdAt) - new Date(a.createdAt));
    } else if (type === "standard") {
      allAssessments = formatAssessments(standardAssessments, false);
    } else if (type === "sat") {
      allAssessments = formatAssessments(satAssessments, true);
    }

    console.log("✅ Final assessments:", allAssessments.length);

    res.json({
      success: true,
      schoolName: schoolName,
      schoolId: schoolId,
      assessments: allAssessments,
      pagination: {
        total: totalStandard + totalSat,
        page: parseInt(page),
        limit: parseInt(limit),
        pages: Math.ceil((totalStandard + totalSat) / parseInt(limit))
      },
      summary: {
        standard: totalStandard,
        sat: totalSat,
        total: totalStandard + totalSat
      }
    });
  } catch (error) {
    console.error("❌ Error fetching school uploads:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch teacher-generated assessments",
      error: error.message
    });
  }
});

// @desc    Get upload statistics for school admin dashboard
// @route   GET /api/school-admin/uploads/stats
// @access  Private (School Admin or Platform Admin)
const getUploadStats = asyncHandler(async (req, res) => {
  try {
    const userId = req.user._id;
    const userRole = req.user.role;

    // ✅ Get school info based on user role
    const schoolInfo = await getSchoolInfo(userId, userRole);

    if (!schoolInfo) {
      return res.status(400).json({
        success: false,
        message: "Unable to determine school context"
      });
    }

    const { schoolId, schoolName } = schoolInfo;

    console.log("📊 Getting upload stats for school:", schoolName);

    // Find teachers in this school
    const teachers = await Teacher.find({
      schoolId: schoolId
    }).select("_id");

    const teacherIds = teachers.map(teacher => teacher._id);

    console.log(`📊 Found ${teacherIds.length} teachers`);

    if (teacherIds.length === 0) {
      return res.json({
        success: true,
        stats: {
          overall: {
            totalUploads: 0,
            approved: 0,
            pending: 0,
            activeTeachers: 0,
            recentUploads: 0
          },
          standard: {
            total: 0,
            approved: 0,
            pending: 0,
            recent: 0
          },
          sat: {
            total: 0,
            approved: 0,
            pending: 0,
            recent: 0
          }
        }
      });
    }

    const [standardStats, satStats, recentStandard, recentSAT, activeTeachers] = await Promise.all([
      // Standard assessment stats
      AssessmentUpload.aggregate([
        { $match: { teacherId: { $in: teacherIds } } },
        { $group: { _id: "$isApproved", count: { $sum: 1 } } }
      ]),
      // SAT assessment stats
      SatAssessment.aggregate([
        { $match: { teacherId: { $in: teacherIds } } },
        { $group: { _id: "$isApproved", count: { $sum: 1 } } }
      ]),
      // Recent standard (last 7 days)
      AssessmentUpload.countDocuments({
        teacherId: { $in: teacherIds },
        createdAt: { $gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) }
      }),
      // Recent SAT (last 7 days)
      SatAssessment.countDocuments({
        teacherId: { $in: teacherIds },
        createdAt: { $gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) }
      }),
      // Active teachers count
      Teacher.countDocuments({
        schoolId: schoolId,
        status: "approved"
      })
    ]);

    console.log("📊 Standard Stats:", standardStats);
    console.log("📊 SAT Stats:", satStats);

    // Calculate totals
    const approvedStandard = standardStats.find(s => s._id === true)?.count || 0;
    const pendingStandard = standardStats.find(s => s._id === false)?.count || 0;
    const totalStandard = approvedStandard + pendingStandard;

    const approvedSAT = satStats.find(s => s._id === true)?.count || 0;
    const pendingSAT = satStats.find(s => s._id === false)?.count || 0;
    const totalSAT = approvedSAT + pendingSAT;

    res.json({
      success: true,
      stats: {
        overall: {
          totalUploads: totalStandard + totalSAT,
          approved: approvedStandard + approvedSAT,
          pending: pendingStandard + pendingSAT,
          activeTeachers: activeTeachers,
          recentUploads: recentStandard + recentSAT
        },
        standard: {
          total: totalStandard,
          approved: approvedStandard,
          pending: pendingStandard,
          recent: recentStandard
        },
        sat: {
          total: totalSAT,
          approved: approvedSAT,
          pending: pendingSAT,
          recent: recentSAT
        }
      }
    });
  } catch (error) {
    console.error("❌ Error fetching upload stats:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch upload statistics",
      error: error.message
    });
  }
});

// @desc    Get detailed view of a specific uploaded assessment
// @route   GET /api/school-admin/uploads/:id
// @access  Private (School Admin or Platform Admin)
const getUploadDetails = asyncHandler(async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user._id;
    const userRole = req.user.role;

    // ✅ Get school info based on user role
    const schoolInfo = await getSchoolInfo(userId, userRole);

    if (!schoolInfo) {
      return res.status(400).json({
        success: false,
        message: "Unable to determine school context"
      });
    }

    const { schoolId } = schoolInfo;

    // Find teachers in this school
    const teachers = await Teacher.find({
      schoolId: schoolId
    }).select("_id");

    const teacherIds = teachers.map(teacher => teacher._id);

    console.log("🔍 Getting upload details for assessment:", id);
    console.log("🔍 Teacher IDs in school:", teacherIds.length);

    if (teacherIds.length === 0) {
      return res.status(404).json({
        success: false,
        message: "No teachers found in your school"
      });
    }

    // Try standard assessment first
    let assessment = await AssessmentUpload.findOne({
      _id: id,
      teacherId: { $in: teacherIds }
    })
      .populate({ path: "teacherId", select: "name email" })
      .lean();

    let assessmentType = "standard";

    // Try SAT assessment if not found
    if (!assessment) {
      assessment = await SatAssessment.findOne({
        _id: id,
        teacherId: { $in: teacherIds }
      })
        .populate({ path: "teacherId", select: "name email" })
        .lean();
      assessmentType = "sat";
    }

    if (!assessment) {
      console.log("❌ Assessment not found or not in this school");
      return res.status(404).json({
        success: false,
        message: "Assessment not found in your school"
      });
    }

    console.log("✅ Assessment found:", assessment.assessmentName || assessment.satTitle);

    // Get submission stats
    const SubmissionModel = assessmentType === "standard" ? AssessmentSubmission : SatSubmission;
    const submissionStats = await SubmissionModel.aggregate([
      { $match: { assessmentId: assessment._id } },
      {
        $group: {
          _id: null,
          totalAttempts: { $sum: 1 },
          avgPercentage: { $avg: "$percentage" },
          avgTimeTaken: { $avg: "$timeTaken" },
          bestScore: { $max: "$percentage" }
        }
      }
    ]);

    const stats = submissionStats[0] || {
      totalAttempts: 0,
      avgPercentage: 0,
      avgTimeTaken: 0,
      bestScore: 0
    };

    // Calculate total marks
    const totalMarks = assessment.questions
      ? assessment.questions.reduce((sum, q) => sum + (q.marks || 1), 0)
      : 0;

    // ✅ FIXED: Return the actual questions array, not just the count
    const formattedAssessment = {
      _id: assessment._id,
      type: assessmentType,
      name: assessmentType === "standard" ? assessment.assessmentName : assessment.satTitle,
      title: assessmentType === "standard" ? assessment.assessmentName : assessment.satTitle,
      subject: assessmentType === "standard" ? assessment.subject : assessment.sectionType,
      difficulty: assessment.difficulty,
      gradeLevel: assessment.gradeLevel || "N/A",
      timeLimit: assessment.timeLimit,
      isApproved: assessment.isApproved,
      status: assessment.status || "draft",
      createdAt: assessment.createdAt,
      teacher: {
        _id: assessment.teacherId?._id || assessment.teacherId,
        name: assessment.teacherId?.name || "Unknown",
        email: assessment.teacherId?.email || "No Email"
      },
      // ✅ CRITICAL FIX: Return the actual questions array
      questions: assessment.questions || [],
      totalMarks: totalMarks,
      fileType: assessment.fileType || "pdf",
      tags: assessment.tags || [],
      rating: assessment.rating || { average: 0, count: 0 },
      questionCount: assessment.questions?.length || 0,
      statistics: {
        totalAttempts: stats.totalAttempts,
        averagePercentage: parseFloat(stats.avgPercentage.toFixed(2)) || 0,
        averageTimeTaken: parseFloat(stats.avgTimeTaken.toFixed(2)) || 0,
        bestScore: parseFloat(stats.bestScore.toFixed(2)) || 0
      }
    };

    res.json({ success: true, assessment: formattedAssessment });
  } catch (error) {
    console.error("❌ Error fetching upload details:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch assessment details",
      error: error.message
    });
  }
});

const exportAssessmentPDF = asyncHandler(async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user._id;
    const userRole = req.user.role;

    const schoolInfo = await getSchoolInfo(userId, userRole);
    if (!schoolInfo) {
      return res.status(400).json({
        success: false,
        message: "Unable to determine school context"
      });
    }

    const { schoolId } = schoolInfo;

    const teachers = await Teacher.find({ schoolId }).select("_id");
    const teacherIds = teachers.map(t => t._id);

    let assessment = await AssessmentUpload.findOne({
      _id: id,
      teacherId: { $in: teacherIds }
    })
      .populate("teacherId", "name email")
      .lean();

    let assessmentType = "standard";

    if (!assessment) {
      assessment = await SatAssessment.findOne({
        _id: id,
        teacherId: { $in: teacherIds }
      })
        .populate("teacherId", "name email")
        .lean();
      assessmentType = "sat";
    }

    if (!assessment) {
      return res.status(404).json({
        success: false,
        message: "Assessment not found"
      });
    }

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${(assessment.assessmentName || assessment.satTitle)
        .replace(/[^a-z0-9]/gi, "_")}_${Date.now()}.pdf"`
    );

    doc.pipe(res);

    /* =====================================================
       PAGE 1 — INTRODUCTION (MATCHES SCREENSHOT)
    ====================================================== */

    // Light blue title background
    doc
      .rect(50, 40, doc.page.width - 100, 70)
      .fill("#eef7ff");

    // Title
    doc
      .fillColor("#1e3a8a")
      .font("Helvetica-Bold")
      .fontSize(26)
      .text(
        assessment.assessmentName || assessment.satTitle,
        50,
        60,
        { width: doc.page.width - 100, align: "center" }
      );

    // Subtitle
    doc
      .font("Helvetica")
      .fontSize(12)
      .fillColor("#334155")
      .text(
        `${assessmentType === "sat" ? "SAT Assessment" : "Standard Assessment"} | ID: ${assessment._id
          .toString()
          .slice(-8)}`,
        50,
        92,
        { width: doc.page.width - 100, align: "center" }
      );

    // Assessment Details title
    doc.moveDown(4);
    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .fillColor("#1e40af")
      .text("Assessment Details");

    doc.moveDown(2);

    const leftX = 60;
    const rightX = 320;
    let startY = doc.y;

    const details = [
      { label: "Subject", value: assessment.subject || assessment.sectionType },
      { label: "Difficulty", value: assessment.difficulty },
      { label: "Grade Level", value: assessment.gradeLevel || "N/A" },
      { label: "Time Limit", value: `${assessment.timeLimit} minutes` },
      { label: "Total Questions", value: assessment.questions.length },
      { label: "Status", value: assessment.isApproved ? "Approved" : "Pending" },
      { label: "Created By", value: assessment.teacherId?.name || "Unknown" },
      { label: "Teacher Email", value: assessment.teacherId?.email || "N/A" },
      {
        label: "Created Date",
        value: new Date(assessment.createdAt).toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric"
        })
      },
      {
        label: "Assessment Type",
        value: assessmentType === "sat" ? "SAT Preparation" : "Standard Curriculum"
      }
    ];

    details.forEach((item, index) => {
      const x = index % 2 === 0 ? leftX : rightX;
      const y = startY + Math.floor(index / 2) * 35;

      doc
        .font("Helvetica-Oblique")
        .fontSize(11)
        .fillColor("#475569")
        .text(`${item.label}:`, x, y, { continued: true });

      doc
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(` ${item.value}`);
    });

    /* =====================================================
       PAGE 2 — QUESTIONS
    ====================================================== */

    doc.addPage();

    doc.moveDown(2);
    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .fillColor("#1e40af")
      .text("Questions");

    doc.moveDown(2);

    assessment.questions.forEach((q, index) => {
      if (doc.y > doc.page.height - 220) {
        doc.addPage();
        doc.moveDown(2);
      }

      // Question text
      doc
        .font("Helvetica-Bold")
        .fontSize(14)
        .fillColor("#111827")
        .text(`Q${index + 1}. ${q.questionText}`);

      doc.moveDown(0.4);

      // Metadata
      doc
        .font("Helvetica-Oblique")
        .fontSize(10)
        .fillColor("#6b7280")
        .text(
          `Type: ${(q.type || "MCQ").toUpperCase()} | Marks: ${q.marks || 1} | Difficulty: ${q.difficulty || "Medium"}`
        );

      doc.moveDown(0.8);

      // Options
      if (q.options?.length) {
        doc.font("Helvetica").fontSize(12).fillColor("#374151").text("Options:");
        q.options.forEach((opt, i) => {
          const isCorrect = i === q.correctAnswer;
          doc
            .font(isCorrect ? "Helvetica-Bold" : "Helvetica")
            .fillColor(isCorrect ? "#065f46" : "#111827")
            .text(`${String.fromCharCode(65 + i)}. ${opt}`, {
              indent: 25
            });
        });
      }

      // Separator
      doc.moveDown(1);
      doc
        .strokeColor("#e5e7eb")
        .lineWidth(1)
        .moveTo(50, doc.y)
        .lineTo(doc.page.width - 50, doc.y)
        .stroke();

      doc.moveDown(1.5);
    });

    doc.end();
  } catch (error) {
    console.error("❌ PDF Export Error:", error);
    if (!res.headersSent) {
      res.status(500).json({
        success: false,
        message: "Failed to export assessment PDF"
      });
    }
  }
});


module.exports = {
  getSchoolUploads,
  getUploadStats,
  getUploadDetails,
  exportAssessmentPDF
};